name = "fs"

[namespace.service.new]
required = ["work_dir"]

[namespace.service.op.create]
optional = ["location"]

[namespace.service.op.delete]
optional = ["location"]

[namespace.service.op.get]
optional = ["location"]

[namespace.service.op.list]
optional = ["location"]

[namespace.storage]
# features = ["virtual_dir", "virtual_link"]
implement = ["copier", "mover", "fetcher", "appender", "direr", "linker"]

[namespace.storage.new]
required = ["name"]
optional = ["work_dir"]

[namespace.storage.op.create]
optional = ["object_mode"]

[namespace.storage.op.delete]
optional = ["object_mode"]

[namespace.storage.op.list]
optional = ["continuation_token", "list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.stat]
optional = ["object_mode"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "offset", "io_callback"]

[pairs.default_service_pairs]
type = "DefaultServicePairs"
description = "set default pairs for service actions"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[pairs.service_features]
type = "ServiceFeatures"
description = "set service features"

[pairs.storage_features]
type = "StorageFeatures"
description = "set storage features"